/*
 * Constants.hpp
 *
 *  Created on: Feb 13, 2018
 *      Author: lfani
 */

#ifndef FACTORY_CONSTANTS_HPP_
#define FACTORY_CONSTANTS_HPP_

static int null = 0;

enum GPIO_BANK{A, B, C, D, E, F};

enum IO_TYPES
{
	PULLDOWN,								// INPUT
	PULLUP,									// INPUT
	PULLDOWN_FILTERED,						// INPUT
	PULLUP_FILTERED,						// INPUT

	OPENSOURCE,								// OUTPUT
	OPENSOURCE_PULLDOWN,					// OUTPUT
	OPENDRAIN_PULLUP,						// OUTPUT
	OPENDRAIN_PULLUP_FILTER,				// OUTPUT
	OPENDRAIN_ATLDRIVE,						// OUTPUT
	OPENDRAIN_ATLDRIVE_FILTER,				// OUTPUT
	OPENDRAIN_ATLDRIVE_PULLUP,				// OUTPUT
	OPENDRAIN_ATLDRIVE_PULLUP_FILTER,		// OUTPUT
	PUSHPULL,								// OUTPUT
	PUSHPULL_ALTDRIVE						// OUTPUT
};

static int ACCELEROMETER_ADDRESS = 85; // 0x55

#endif /* FACTORY_CONSTANTS_HPP_ */
