/*
 * Constants.hpp
 *
 *  Created on: Feb 13, 2018
 *      Author: lfani
 */

#ifndef FACTORY_CONSTANTS_HPP_
#define FACTORY_CONSTANTS_HPP_

#define null 0

enum GPIO_BANK{A, B, C, D, E, F};
enum STATES_GLOBAL{CREATED, INPUT, OUTPUT, CONFIGURED, DELETED};
enum I_TYPES{PULLDOWN,
			PULLUP,
			PULLDOWN_FILTERED,
			PULLUP_FILTERED};
enum O_TYPES{OPENSOURCE,
			OPENSOURCE_PULLDOWN,
			OPENDRAIN_PULLUP,
			OPENDRAIN_PULLUP_FILTER,
			OPENDRAIN_ATLDRIVE,
			OPENDRAIN_ATLDRIVE_FILTER,
			OPENDRAIN_ATLDRIVE_PULLUP,
			OPENDRAIN_ATLDRIVE_PULLUP_FILTER,
			PUSHPULL,
			PUSHPULL_ALTDRIVE};

#endif /* FACTORY_CONSTANTS_HPP_ */
